slack_channels:
- dev-infrastructure
security:
  data_management:
    contains_pii: false
ci_url: https://buildkite.com/shopify/go-cache-ci
bugs_url: https://github.com/Shopify/go-cache/issues
production:
  classification: library
